export interface LeaderboardEntry {
  id: string;
  rank: number;
  name: string;
  points: number;
  prize: string;
  avatar: string;
  isCurrentUser?: boolean;
}

export const leaderboardData: LeaderboardEntry[] = [
  {
    id: "1",
    rank: 1,
    name: "Alex Thompson",
    points: 500,
    prize: "2,125,000 $VS",
    avatar: "/icon/avatar1.svg",
  },
  {
    id: "2",
    rank: 2,
    name: "Sarah Johnson",
    points: 450,
    prize: "2,005,000 $VS",
    avatar: "/icon/avatar2.svg",
  },
  {
    id: "3",
    rank: 3,
    name: "Mike Chen",
    points: 425,
    prize: "1,995,000 $VS",
    avatar: "/icon/avatar3.svg",
  },
  {
    id: "4",
    rank: 4,
    name: "Emma Wilson",
    points: 400,
    prize: "1,975,000 $VS",
    avatar: "/icon/avatar4.svg",
  },
  {
    id: "5",
    rank: 5,
    name: "David Brown",
    points: 390,
    prize: "1,920,000 $VS",
    avatar: "/icon/avatar5.svg",
  },
  {
    id: "6",
    rank: 6,
    name: "Lisa Garcia",
    points: 375,
    prize: "1,875,000 $VS",
    avatar: "/icon/avatar6.svg",
  },
  {
    id: "7",
    rank: 7,
    name: "James Miller",
    points: 360,
    prize: "1,830,000 $VS",
    avatar: "/icon/avatar7.svg",
  },
  {
    id: "8",
    rank: 8,
    name: "Maria Rodriguez",
    points: 345,
    prize: "1,785,000 $VS",
    avatar: "/icon/avatar8.svg",
  },
  {
    id: "9",
    rank: 9,
    name: "Robert Taylor",
    points: 330,
    prize: "1,740,000 $VS",
    avatar: "/icon/avatar9.svg",
  },
  {
    id: "10",
    rank: 10,
    name: "Jennifer Lee",
    points: 315,
    prize: "1,695,000 $VS",
    avatar: "/icon/avatar10.svg",
  },
  {
    id: "11",
    rank: 11,
    name: "Christopher Anderson",
    points: 300,
    prize: "1,650,000 $VS",
    avatar: "/icon/avatar11.svg",
  },
  {
    id: "12",
    rank: 12,
    name: "Amanda White",
    points: 285,
    prize: "1,605,000 $VS",
    avatar: "/icon/avatar12.svg",
  },
  {
    id: "13",
    rank: 13,
    name: "Daniel Harris",
    points: 270,
    prize: "1,560,000 $VS",
    avatar: "/icon/avatar13.svg",
  },
  {
    id: "14",
    rank: 14,
    name: "Jessica Martin",
    points: 255,
    prize: "1,515,000 $VS",
    avatar: "/icon/avatar14.svg",
  },
  {
    id: "15",
    rank: 15,
    name: "Matthew Thompson",
    points: 240,
    prize: "1,470,000 $VS",
    avatar: "/icon/avatar15.svg",
  },
  {
    id: "16",
    rank: 16,
    name: "Ashley Garcia",
    points: 225,
    prize: "1,425,000 $VS",
    avatar: "/icon/avatar16.svg",
  },
  {
    id: "17",
    rank: 17,
    name: "Andrew Martinez",
    points: 210,
    prize: "1,380,000 $VS",
    avatar: "/icon/avatar17.svg",
  },
  {
    id: "18",
    rank: 18,
    name: "Stephanie Robinson",
    points: 195,
    prize: "1,335,000 $VS",
    avatar: "/icon/avatar18.svg",
  },
  {
    id: "19",
    rank: 19,
    name: "Joshua Clark",
    points: 180,
    prize: "1,290,000 $VS",
    avatar: "/icon/avatar19.svg",
  },
  {
    id: "20",
    rank: 20,
    name: "Nicole Rodriguez",
    points: 165,
    prize: "1,245,000 $VS",
    avatar: "/icon/avatar20.svg",
  },
  {
    id: "21",
    rank: 21,
    name: "Kevin Lewis",
    points: 150,
    prize: "1,200,000 $VS",
    avatar: "/icon/avatar21.svg",
  },
  {
    id: "22",
    rank: 22,
    name: "Michelle Walker",
    points: 135,
    prize: "1,155,000 $VS",
    avatar: "/icon/avatar22.svg",
  },
  {
    id: "23",
    rank: 23,
    name: "Ryan Hall",
    points: 120,
    prize: "1,110,000 $VS",
    avatar: "/icon/avatar23.svg",
  },
  {
    id: "24",
    rank: 24,
    name: "Kimberly Allen",
    points: 105,
    prize: "1,065,000 $VS",
    avatar: "/icon/avatar24.svg",
  },
  {
    id: "25",
    rank: 25,
    name: "Brandon Young",
    points: 90,
    prize: "1,020,000 $VS",
    avatar: "/icon/avatar25.svg",
  },
  {
    id: "26",
    rank: 26,
    name: "Rachel King",
    points: 85,
    prize: "975,000 $VS",
    avatar: "/icon/avatar26.svg",
  },
  {
    id: "27",
    rank: 27,
    name: "Tyler Wright",
    points: 80,
    prize: "930,000 $VS",
    avatar: "/icon/avatar27.svg",
  },
  {
    id: "28",
    rank: 28,
    name: "Samantha Lopez",
    points: 75,
    prize: "885,000 $VS",
    avatar: "/icon/avatar28.svg",
  },
  {
    id: "29",
    rank: 29,
    name: "Jacob Hill",
    points: 70,
    prize: "840,000 $VS",
    avatar: "/icon/avatar29.svg",
  },
  {
    id: "30",
    rank: 30,
    name: "Lauren Scott",
    points: 65,
    prize: "795,000 $VS",
    avatar: "/icon/avatar30.svg",
  },
  {
    id: "31",
    rank: 31,
    name: "Nathan Green",
    points: 60,
    prize: "750,000 $VS",
    avatar: "/icon/avatar31.svg",
  },
  {
    id: "32",
    rank: 32,
    name: "Brittany Adams",
    points: 55,
    prize: "705,000 $VS",
    avatar: "/icon/avatar32.svg",
  },
  {
    id: "33",
    rank: 33,
    name: "Zachary Baker",
    points: 50,
    prize: "660,000 $VS",
    avatar: "/icon/avatar33.svg",
  },
  {
    id: "34",
    rank: 34,
    name: "Megan Nelson",
    points: 45,
    prize: "615,000 $VS",
    avatar: "/icon/avatar34.svg",
  },
  {
    id: "35",
    rank: 35,
    name: "Caleb Carter",
    points: 40,
    prize: "570,000 $VS",
    avatar: "/icon/avatar35.svg",
  },
  {
    id: "36",
    rank: 36,
    name: "Kayla Mitchell",
    points: 35,
    prize: "525,000 $VS",
    avatar: "/icon/avatar36.svg",
  },
  {
    id: "37",
    rank: 37,
    name: "Ethan Perez",
    points: 30,
    prize: "480,000 $VS",
    avatar: "/icon/avatar37.svg",
  },
  {
    id: "38",
    rank: 38,
    name: "Taylor Roberts",
    points: 25,
    prize: "435,000 $VS",
    avatar: "/icon/avatar38.svg",
  },
  {
    id: "39",
    rank: 39,
    name: "Noah Turner",
    points: 20,
    prize: "390,000 $VS",
    avatar: "/icon/avatar39.svg",
  },
  {
    id: "40",
    rank: 40,
    name: "Olivia Phillips",
    points: 18,
    prize: "345,000 $VS",
    avatar: "/icon/avatar40.svg",
  },
  {
    id: "41",
    rank: 41,
    name: "Liam Campbell",
    points: 16,
    prize: "300,000 $VS",
    avatar: "/icon/avatar41.svg",
  },
  {
    id: "42",
    rank: 42,
    name: "Ava Parker",
    points: 14,
    prize: "255,000 $VS",
    avatar: "/icon/avatar42.svg",
  },
  {
    id: "43",
    rank: 43,
    name: "Lucas Evans",
    points: 12,
    prize: "210,000 $VS",
    avatar: "/icon/avatar43.svg",
  },
  {
    id: "44",
    rank: 44,
    name: "Isabella Edwards",
    points: 10,
    prize: "165,000 $VS",
    avatar: "/icon/avatar44.svg",
  },
  {
    id: "45",
    rank: 45,
    name: "Mason Collins",
    points: 8,
    prize: "120,000 $VS",
    avatar: "/icon/avatar45.svg",
  },
  {
    id: "46",
    rank: 46,
    name: "Sophia Stewart",
    points: 6,
    prize: "75,000 $VS",
    avatar: "/icon/avatar46.svg",
  },
  {
    id: "47",
    rank: 47,
    name: "Logan Sanchez",
    points: 4,
    prize: "30,000 $VS",
    avatar: "/icon/avatar47.svg",
  },
  {
    id: "48",
    rank: 48,
    name: "Emma Morris",
    points: 3,
    prize: "15,000 $VS",
    avatar: "/icon/avatar48.svg",
  },
  {
    id: "49",
    rank: 49,
    name: "Jackson Rogers",
    points: 2,
    prize: "5,000 $VS",
    avatar: "/icon/avatar49.svg",
  },
  {
    id: "50",
    rank: 50,
    name: "John Doe",
    points: 1,
    prize: "2,000 $VS",
    avatar: "/icon/avatar50.svg",
    isCurrentUser: true,
  },
];
