import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Sidebar } from "@/components/layout/Sidebar";
import { Footer } from "@/components/layout/Footer";
import { GoogleOAuthProviderWrapper } from "@/components/auth/GoogleOAuthProvider";
import { AuthProvider } from "@/components/auth/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProviderWrapper>
          <AuthProvider>
            <div className="flex min-h-screen flex-col bg-gradient-to-b from-[#181b31] via-[#232149] via-[#202042] to-[#181b31] text-white">
              <Header />
              <div className="flex w-full flex-1">
                <Sidebar />
                <main className="min-h-[60vh] flex-1 border border-white/10 bg-transparent p-4">
                  {children}
                </main>
              </div>
              {/* <Footer /> */}
            </div>
          </AuthProvider>
        </GoogleOAuthProviderWrapper>
      </body>
    </html>
  );
}
